#SERVER SETTINGS
SERVER_HOST_NAME          = "0.0.0.0" ##THE IP ADDRESS FOR GALAKSIO, LEAVE 0.0.0.0 FOR LISTENING ALL REQUESTS
SERVER_PORT_NUMBER        = 8081 ##THE PORT NUMBER THAT GALAKSIO LISTENS FOR REQUESTS
SERVER_ALLOW_DEBUG        = False ##ENABLE DEBUG, THIS OPTIOS IS JUST FOR DEVELOPMENT
SERVER_SUBDOMAIN          = "" ##USE THIS OPTION IF GALAKSIO RUNS UNDER AN SPECIFIC SUBDOMAIN, E.G. myserver.com/galaksio (w/o proxy)
SERVER_MAX_CONTENT_LENGTH = 20 ##THE MAX SIZE FOR THE REQUESTS SENT BY THE CLIENTS, IN MB
ADMIN_ACCOUNTS            = "myadmin@galaksio.com" ##ACCOUNTS THAT HAVE ADMINISTRATION RIGHTS, SEPARATED BY COMMAS

#FILES SETTINGS
ROOT_DIRECTORY            = "" ##THE LOCATION FOR THE GALAKSIO FILES, LEAVE BLANK TO AUTO DETECT

#GALAXY SETTINGS
GALAXY_SERVER             = "https://usegalaxy.org" ##THE INTERNAL URL OR IP FOR THE GALAXY INSTANCE THAT WILL RECEIVE ALL THE GALAKSIO REQUESTS
GALAXY_SERVER_URL         = "" ##THE EXTERNAL URL FOR THE GALAXY INSTANCE, LEAVE EMPTY IF IT IS THE SAME THAN GALAXY_SERVER
