version: '2'
services:

    instance1-galaksio:
      image: fikipollo/galaksio
      container_name: instance1-galaksio
      environment:
        - GALAXY_SERVER=https://usegalaxy.eu
        - GALAXY_SERVER_URL=https://usegalaxy.eu
        - MAX_CONTENT_LENGTH=300
        - ADMIN_ACCOUNTS=myadmin@email.com
      volumes_from:
        - instance1-galaksio-data
      ports:
        - "8081:80"

    instance1-galaksio-data:
      image: busybox
      container_name: instance1-galaksio-data
      volumes:
        - /data/instance1-data/galaksio-data:/usr/local/apache2/htdocs/server/conf/
